sassoftware/viya4-iac-azure

README.md

Updated the doc to reflect the need for the jq binary when running terraform natively. This is not an issue when running with docker as this already addressed.

Added in jq dep text

---

README.md

The tfvars file used in the docker examples should be the same in the terraform examples, and match the instructions for creating the tvars file, which uses terraform.tfvars

docker tfvars files doc

---

modules/azure_aks/main.tf

Removed label from default node pool which was causing terraform idempotent issues.

Removed system label from default node pool

---

examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
files/sas-iac-buildinfo.yaml.tmpl
main.tf
modules/aks_node_pool/main.tf
modules/azurerm_netapp/main.tf
modules/azurerm_netapp/outputs.tf
modules/azurerm_vm/main.tf
modules/azurerm_vm/outputs.tf
modules/azurerm_vm/variables.tf
modules/azurerm_vnet/main.tf
modules/azurerm_vnet/outputs.tf
modules/azurerm_vnet/variables.tf
outputs.tf
variables.tf

close - #106 - remove kubernetes_provider that causes the issue and revert back to template file and null_resource
close - #108 - AKS updates no longer are triggered on changes to `tags`, more on that below, however in a few NFS update paths can hit - https://github.com/Azure/terraform-azurerm-compute/issues/107 
close - #109 - add tags to ACR
Added local module for azurerm_vnet to avoid https://github.com/Azure/terraform-azurerm-vnet/issues/41. In digging through this, it's an issue with multiple data source objects which doesn't have 'tags' attribute. TF sees this as a difference and with `depends_on` does a forced replacement of resources - Subnets, AKS etc. These changes solves any unwanted forced replacement and does an in place update to resources triggered due to changes to 'tags'

Fixed dependency issues

---

docs/CONFIG-VARS.md
variables.tf

Closes #150 by now requiring the `prefix` value contain only lowercase values.

Added prefix validation check and doc updates

---

docs/user/AzureHelpTopics.md

When following the instructions as written, the two variables had quotes around the values, which resulted in errors in the next steps. Adding the sed command to remove leading/trailing double quotes resolved the error.

Add --output tsv to TF VAR tenant and subscription IDs

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
variables.tf

- Default 'kubernetes_version' updated to 1.21.7
- All example files update to reflect the same
- Verified on Azure with default K8s v1.21.7, viya4 deployment, logging and monitoring were successful.

(IAC-395) Updated default Kubernetes version from 1.19 -> 1.21

---

.pre-commit-config_template.yaml
.tflint.hcl

Why:
Wish to enable use of existing linter static checks, and any other new ones from developer sandbox.
In an effort to shift left static lint checks already in place for Azure IaC GitHub repo PR/merges
**Note:** This PR also includes the update for IAC-421 which updates the tflint tool configuration and touches the same file that IAC-407 requires.

(IAC-407) feature: Enable running static checks in Azure IaC repo via pre-commit tool

---

docs/CONFIG-VARS.md
modules/azure_aks/variables.tf
variables.tf

There is an error in the variables.tf with the default location (=Azure region). When not specifying a location file and using the default your terraform apply will fail like this:
```
│ Error: "resource_group_name" may only contain alphanumeric characters, dash, underscores, parentheses and periods
│
│   with module.aks.data.azurerm_public_ip.cluster_public_ip[0],
│   on modules/azure_aks/main.tf line 111, in data "azurerm_public_ip" "cluster_public_ip":
│  111:  data "azurerm_public_ip" "cluster_public_ip" {
```
The cause of that is on line https://github.com/sassoftware/viya4-iac-azure/blob/main/modules/azure_aks/main.tf#L116 where it says `resource_group_name = "MC_${var.aks_cluster_rg}_${var.aks_cluster_name}_${var.aks_cluster_location}"`
The `var.aks_cluster_location` is built from …

(IAC-449) Fix location to drop space else deployment fails

---

docs/user/BYOnetwork.md

* Updates the BYO Subnet documentation to make it clear that if the user opts for an external Postgres instance they will need to define service endpoints in their subnets.
* Minor doc formatting/cleanup

(IAC-374) Update BYO Subnet Documentation

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
variables.tf

Since Viya will be supporting 1.21, 1.22, and 1.23 in June, the kubectl version is being changed to 1.22 so that it's within the +/- 1 range of the supported versions. The default version in the example .tfvars is also being changed to 1.22.6
so that it is also in the middle of the support version range. 
Test summary, more detail is present in the internal ticket.
| Cloud Provider | kubectl version | K8s Version | Cadence   | Ingress-nginx version | Deployment Stabilized |
|----------------|-----------------|-------------|-----------|-----------------------|-----------------------|
| Azure          | 1.22.10         | 1.22.6      | Fast:2020 | v1.1.1                | Yes                   |
| Azure          | 1.22.10         | 1.22.6      | 2022.1.1  | v1.1.1                | Yes …

(IAC-543) Update kubectl and default K8s version to 1.22

---

docs/CONFIG-VARS.md

Updated note in the 'Additional Node Pools' section of CONFIG-VARS.md to indicate the required variables for each node pool.

doc: (IAC-595) max_pods note in the additional-node-pools

---

files/cloud-init/nfs/cloud-config

NFS mount failed when AKS and misc CIDR blocks are the same. To resolve the issue If-else logic was added to avoid the duplicate exports.
Stephen's comment:
I have gone ahead and went back to the clear formatting that was asked for, and tested this change in both situations (VPN cluster on private mode and regular mode). Both seem to work well. Feel free to use this how you want.
Following scenarios were verified, see the internal ticket for details
**Scenario 1**: AKS and misc CIDR block are the same
**Scenario 2**: AKS and misc CIDR block are the different
**Scenario 3**: default setting for AKS and misc CIDR blocks

fix: (IAC-506) Modified if-else logic to be readable and avoid duplicates

---

examples/sample-input-singlestore.tfvars

Summary:
- Move singlestore node pool to the end per review comment
- bump kubernetes_version to 1.22.6 since SingleStore operator requires
K8S 1.22 or later

(IAC-451) Add singlestore support to Azure IAC 

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
modules/kubeconfig/main.tf
variables.tf
versions.tf

Starting from Kubernetes version `1.24.0` service account token is not automatically generated, thus it has to be created separately. The following resources were updated by the provider `hashicorp/kubernetes` to handle this change in `v2.13.0`: `d/kubernetes_service_account`, `r/kubernetes_default_service_account`, `r/kubernetes_service_account`. For Kubernetes clusters running v1.24+ `default_secret_name` will be empty. A warning message will be printed once any of the above resources are in use. 
- To support 1.24+ Kubernetes version in AKS, secret is manually created for the service account
- The default K8s value is updated from 1.22.6 to 1.23.8
- Minor warning fix for provider `hashicorp/azuread`
1. Verified cluster creation with K8s version: 1.24.0 was successful. Viya deployment …

feat: (IAC-583): AKS add support for K8s 1.24

---

TODO.md
docs/CONFIG-VARS.md
locals.tf
main.tf
modules/azurerm_postgresql_flex/main.tf
modules/azurerm_postgresql_flex/outputs.tf
modules/azurerm_postgresql_flex/variables.tf
outputs.tf
variables.tf

- Changes made to support the PostgreSQL flexible server for Azure using the [terraform azurerm_postgresql_flexible_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server)
- Default `server_version` value updated from 11 to 13. Variable `postgres_server_defaults` adjusted to map version value to 13.
- The user can select any version between 11-14 to suite their SAS Viya deployment requirements.
Verified the following deployment scenarios, please see internal ticket for details.
| Scenario | Provider | K8s Version | PG Version | Order | Cadence | Deployment Stabilized | Notes |
|---|---|---|---|---|---|---|---|
| PostgreSQL V11 | Azure | 1.23.8 | 11.16 | * | Fast:2020 | Yes  | |
| PostgreSQL V12 | Azure | 1.23.8 | 12.11 | * | …

feat: (IAC-91) Support of Azure DB for PostgreSQL flexible server

---

docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
variables.tf

- Renamed the missed "nfs_raid_disk_zones" to "nfs_raid_disk_zone"
- Removed the reference of "create_aks_azure_monitor" from example sample files, as this is an undocumented feature.

docs: (IAC-403): documentation updates

---

examples/sample-input-minimal.tfvars

The current minimally sized cluster sample file does not allow for reliable successful deployment of cluster-logging and Viya and sometimes result in a failed logging deployment with errors indicating that insufficient initial cluster resources are the cause.
Increasing the default node count and default vm size in the current minimally sized cluster sample values to 
```
default_nodepool_min_nodes = 2
default_nodepool_vm_type  = "Standard_D4_v3"
```
remedies the problem for a marginally small increase in cost.
Ran three consecutive deployments ("cluster-logging,viya,install") against an Azure cluster starting out each time with only the 2 default nodes sized as indicated above. Each time cluster-logging deployed without errors and all logging namespace pods reached the Running status. …

feat: (IAC-438) Increase default node count and size for minimal cluster config

---

docs/CONFIG-VARS.md
variables.tf

Updated the `min_nodes` to 1 for `compute` node in variables.tf and CONFIG-VARS.md node_pool example.
With `min_nodes` set to 1 for `compute` node, verified the cluster was created with 1 compute node and 2 system nodes. After running the viya4-deployment all the pods initially started on `stateful` node, later `cas` node was created. After deployment stabilized logged in to SASStudio, compute context check was successful, SASStudio was usable.

docs: (IAC-697): Updated the min_nodes value for compute node to 1

---

docs/CONFIG-VARS.md
main.tf
modules/azure_aks/main.tf
modules/azure_aks/variables.tf
variables.tf

This adds aks_cluster_sku_tier to variables.tf. Choosing "Free" (the default) results in a cluster "optimized for availability". Choosing "Paid" optimizes for availability (and cost more $).  (case sensitive).  Default behavior does not change. Tested and working.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#sku_tier

feat: (IAC-639):  Implement aks_cluster_sku_tier 

---

examples/sample-input-singlestore.tfvars

Deployments with SingleStore configuration and HA storage type are running into issues. The netapp_network_features has default value of `Basic`, the 1000 IP address limit that ANF has OOTB isn't enough and times out.
The solution is to use `netapp_network_features = Standard` in case of S2 configuration with HA. Updated the SingleStore example file to add comment about the same.
Note: Without S2 configuration HA works fine with `netapp_network_features = Basic`.

docs: (IAC-812): Updated S2 example file For SingleStore configuration with HA storage

---

monitor.tf
variables.tf

New optional diagnostic setting resource block included in the aks module. Disabled by default, optionally enabled if and only if `create_aks_azure_monitor` is enabled. This diagnostic setting is connected to the aks cluster and configured to send diagnostic data to the log analytics workspace.
Changes were made following the terraform doc for this resource:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting 
Following scenarios were verified, see details in internal ticket.
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|In terraform.tfvars set create_aks_azure_monitor = True|Fast 2020|Diagnostic settings were enabled for the aks cluster and data was sent to log analytics workspace . Viya4 deployment …

feat: (IAC-638): Added new optional Diagnostic Setting for AKS clusters

---

variables.tf

Added validation for `resource_log_category` and `metric_category` variable. The variables have default so it's not mandatory to provide values but specifying empty list will throw validation errors for both the variables.
Specifying empty lists for `resource_log_category` and `metric_category` throws expected error

feat: (IAC-638): Updated variable description and validation blocks

---

docs/CONFIG-VARS.md
main.tf
variables.tf

- Allow IaC users to specify a list of availability zones for AKS worker node pools
- Feature introduces parity between system and worker node pool. Both pools now support a user-defined list of availability zones
- Change introduces var `node_pools_availability_zones` while preserving singular variant `node_pools_availability_zone`
- Existing variable will be honored and given priority
- Need to consider eventual deprecation of `node_pools_availability_zone`
Verified the following scenarios:
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|Create cluster with new variable node_pools_availability_zones as list|Fast 2020|Cluster creation with multi-zone setup was successful. Viya4 deployment on the aks cluster stabilized and applications are accessible| …

feat: (IAC-793): support multiple worker/agent availability zones

---

files/cloud-init/nfs/cloud-config

Updated the cloud-init file for nfs to address issue with raid device names being switched and mounts being missing between NFS VM restarts and or terraform (re)apply scenarios
Verified following scenarios, see details in internal ticket:
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|NFS VM reboot|Fast 2020|Mounts were correctly bound even after restarts. Viya4 deployment was stable and accessible|
|2|Terraform reapply (see detailed steps in ticket)|Fast 2020|Mounts were correctly bound. Viya4 deployment was stable and accessible|

feat: (IAC-804): Use device UUID in mount to avoid NFS issues due to restarts

---

files/cloud-init/nfs/cloud-config

- (#277) was accidently merged to main branch instead of staging. 
This reverts commit 961d243c71294c26e9005c5275edfa25b5d3dc4e.

Revert "feat: (IAC-804): Use device UUID in mount to avoid NFS issues due to restarts"

---

variables.tf

Terraform version 1.0.0 throws error on the multi-line validation error message. This change updates the error message to a single full sentence.
- No error is thrown on running with terraform v1.0.0

fix: (IAC-905): Change multi-line error message to single line message

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
variables.tf

Update the kubernetes_version default value to 1.23.12. 
The old version 1.23.8 is no longer available in over half the Azure locations.
Verified that the new kubernetes_version default of 1.23.12 produced a cluster that we could successfully perform a SAS Viya Platform deployment on
|Scenario|Deployment Method|Security|K8s Version|Orchestration|Provider|Cadence|Postgres|V4_DEPLOYMENT_OPERATOR_ENABLED|
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
|1|docker|full-stack|v1.23.12|DO|Azure|fast:2020|internal|TRUE||

feat: (IAC-899) Update kubernetes_version to 1.23.12 

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
variables.tf

With SAS Viya Platform supporting K8s 1.23, 1.24, and 1.25 in 2023.03 March release cadence, updating our supported kubectl version to 1.24.10 for it to be in the +/- 1 range of the supported versions.
In this change we are also dropping the patch version requirement for the `kubernetes_version`. All the files are updated to use the format `major.minor` for `kubernetes_version`.
**Note:** Use of exact version is still supported, for exact kubernetes version you can still specify the version as `x.y.z`, where `x` is the major version, `y` is the minor version, and `z` is the patch version.
Verified following scenarios, see details in internal ticket:
|Scenario|Task|Provider|Cadence|kubernetes_version|Actual Kubernetes Cluster Version|Orchestration|kubectl Version| …

feat: (IAC-900): add K8s 1.25 support, set kubectl default to 1.24

---

modules/azurerm_vm/main.tf

Updated the regex to correctly enable network acceleration for NFS VM.
**Note:**
Enabling the network acceleration flag does not incur additional cost. The pricing of VM is still determined based on the type of VM instance you choose. For details about Network acceleration see [here](https://learn.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview).
The default NFS VM type is currently set to `Standard_D8s_v4` and has capability to enable network acceleration.
Verified network acceleration was set to true for the NFS VM only. Cluster creation and SAS Viya Platform deployment was successful. For details see internal ticket.

fix: (IAC-668) enable network acceleration correctly for NFS VM

---

.github/workflows/linter-analysis.yaml

Updated the secret name  from `LINTER_TEST_TOKEN` to `LINTER_TOKEN`.
Verified the new `LINTER_TOKEN` was used to run the GitHub Actions.

feat: (IAC-1062) Update linter secret name

---

main.tf
modules/azurerm_message_broker/main.tf
modules/azurerm_message_broker/outputs.tf
modules/azurerm_message_broker/variables.tf
outputs.tf
variables.tf

Support added for Message broker: `Azure service bus` to be used by SAS Viya Platform deployment.
Resources added using:
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace_authorization_rule
Verified following on the scenarios listed below, please see internal ticket for details.
- Verified cluster creation was successful.
- Azure Service bus was created. 
- SAS Viya Platform consumed the Azure service bus information from state file correctly. 
- Rabbitmq pods were not created.
**Note:** SAS Viya Platform services are still not ready. Almost all pods stabilized except for few services. Launcher service is failing with …

feat: (IAC-1020) Support for Message Broker - Azure Service Bus

---

docs/CONFIG-VARS.md
docs/Troubleshooting.md
files/cloud-init/nfs/cloud-config
modules/azurerm_netapp/variables.tf
variables.tf
vms.tf

NFS version default is now updated to v4.1 for both `storage_type = "standard"` and `storage_type = "ha"`.
Previously the `vers` value was hardcoded to `3`, which caused NFS mounts to fail when `netapp_protocols` is set to NFSv4.1. 
This PR reads the value set and replaces the `vers` parameter. Also added note in Troubleshooting.md for file lock issue seen with NFSv3.
This is a breaking change. Upgrading an existing infrastructure that has SAS Viya Platform deployed on it will result in data loss. The changes in this PR destroy and create the NFS VM or Azure NetApp Volume when upgraded, which will result in data loss affecting your existing SAS Viya Platform deployment. 
To avoid SAS Viya Platform deployment data loss perform backup before upgrading, see details in [SAS …

feat!: (IAC-1021) NFS version default updated to 4.1

---

files/cloud-init/jump/cloud-config
outputs.tf

When a new jump server vm is created, it sets file ownership and permissions for the mounted NFS location which allows Viya services to initialize successfully. Importantly, the file system settings should only be applied once and not repeatedly in the event that the jump vm is destroyed and recreated in the same cluster. This change checks if the `${jump_rwx_filestore_path}/pvs` folder already exists and skips creating the folder and recursively setting ownerships and permissions if it does. If the jump vm is being created for the first time when the pvs folder is absent, creating the folder and setting permissions and ownership will occur an initial time and not thereafter.
This issue originated from AWS, but is applicable for all cloud providers. See the original fix in [AWS …

fix: (IAC-1090) Fixed jumpvm cloud-init causing Viya deployment failure

---

versions.tf

The current terraform `azurerm` provider version `3.54.0` doesn't support Flexible PostgreSQL Server v15. Terraform provider added support for the same in `v3.59.0.`
This PR updates the provider `azurerm` version to latest which `v3.64.0` as of now. Also updated `azuread` version for consistency with the current available version.
Verified following scenarios, see internal ticket for details
|Scenario|Description|Order Cadence|Verification|
|:----|:----|:----|:----|
|1|Default, external PostgreSQL version 15|Fast 2020|Flexible Postgres Server was created with version 15. Viya4 deployment stabilized and was accessible|
|2|Default, internal PostgreSQL, Standard SKU-tier, Azure NetApp default `NFSv4.1`|Fast 2020|Cluster was created successfully. Baseline tasks were successful, Viya4 …

feat: (IAC-1100) Update terraform azurerm provider version to support flexible postgreSQL version 15

---

files/cloud-init/jump/cloud-config

The necessary changes required for preventing Jump VM cloud-init from overwriting existing file permissions/ownership were added in PR #327. This PR adds comments to provide additional context around the same.

docs: (IAC-1138) jump server cloud-init file permissions & ownership

---

docs/CONFIG-VARS.md
modules/azurerm_vm/main.tf
modules/azurerm_vm/variables.tf
variables.tf
vms.tf

8.2.0 - September 21, 2023

---

docs/CONFIG-VARS.md

Updated the incorrect storage_mb default value for Flexible PostgreSQL server in CONFIG-VARS

docs: (IAC-1157) updated incorrect storage_mb default value in CONFIG-VARS

---

outputs.tf

Starting Kubernetes version `1.25` the north-south traffic in Azure stopped working. There were no changes to `azure-ip-masq-agent` or `coredns`. On investigating further found out that changes were made to Azure's standard Loadbalancer. See the following note in [AKS public standard load balancer documentation](https://learn.microsoft.com/en-us/azure/aks/load-balancer-standard#restrict-inbound-traffic-to-specific-ip-ranges)
To enable the North-South traffic again for AKS clusters, adding the `aks_pod_cidr` to terraform output for viya4-deployment to consume the changes.
Verified `aks_pod_cidr` was included in terraform.tfstate file

fix: (IAC-1072) Enabling North-South traffic

---

main.tf

Update the code to resolve `terraform_deprecated_lookup` linting issues 
doc: https://github.com/terraform-linters/tflint-ruleset-terraform/blob/v0.5.0/docs/rules/terraform_deprecated_lookup.md
Created infrastructure and ensured the `sas-iac-buildinfo` was present
```
$ kubectl get cm -n kube-system sas-iac-buildinfo -o yaml
apiVersion: v1
data:
git-hash: 6471f1f2fc6edf1701a2d93fc2dc41d9073199d9
iac-tooling: terraform
terraform: |
version: "1.4.5"
revision: null
provider-selections: {"registry.terraform.io/hashicorp/azuread":"2.39.0","registry.terraform.io/hashicorp/azurerm":"3.64.0","registry.terraform.io/hashicorp/cloudinit":"2.3.2","registry.terraform.io/hashicorp/external":"2.3.1","registry.terraform.io/hashicorp/kubernetes":"2.20.0","registry.terraform.io/hashicorp/local":"2.4.0","reg …
```

chore: (IAC-1238) Resolve TFLint issue

---

docs/CONFIG-VARS.md

Updated the Note in CONFIG-VARS.md to guide user that not setting the CIDR ranges will create a fully public site.

docs: (IAC-802) Added note for setting CIDR range to avoid security violation

---

locals.tf
main.tf

All network related resources should get created into a vnet resource group if supplied by user. VNET gets created correctly in network resource group if `vnet_resource_group_name` is provided however, NSG creation was not following the same pattern. This PR corrects that behavior to follow the same logic.
If `vnet_resource_group_name` is provided without `nsg_name`, IAC will create NSG for you in the provided vnet resource group else NSG will created in the AKS resource group like before.
- fixes #328 
Verified following scenarios, see test details in internal ticket:
| Scenario | Provider | Task          | kubectl version | order  | cadence        |notes|
|----------|----------|-----------------------------|-----------------|--------|------------|------------|
| 1        | Azure      | …

fix: (IAC-1321) updates to create NSG in network rg

---

main.tf
modules/aks_node_pool/main.tf
modules/aks_node_pool/variables.tf
modules/azure_aks/main.tf
modules/azure_aks/variables.tf
modules/azurerm_vm/main.tf
modules/azurerm_vm/variables.tf
variables.tf
vms.tf

This PR adds EncryptAtHost requirements in the VMs and AKS nodes.
- Virtual machines and virtual machine scale sets should have encryption at host enabled.
- Temp disks and cache for agent node pools in AKS clusters should be encrypted at host.
This is an optional features, to enable encryption at host for nodes and VMs you would set the following variables:
| Name | Description | Type | Default |
| :--- | :--- | ---: | ---: |
| enable_vm_host_encryption | Setting this variable enables all of the disks (including the temp disk) attached to this Virtual Machine be encrypted by enabling Encryption at Host. This setting applies to both Jump and NFS VM. | bool | false |
| vm_disk_encryption_set_id | The ID of the Disk Encryption Set which should be used to Encrypt this OS Disk. This setting …

feat: (IAC-1386) EncryptAtHost changes for NIST

---

variables.tf

This PR updates the default probe path from `/SASLogon/apiMeta` to `/SASLogon/login` based on product teams recommendation.
Verified Application gateway creation with default probe was successful. After deploying SAS Viya the backend health of the gateway was healthy. See detailed test result in the internal ticket.

fix: (IAC-1410) Updated the default probe path

---

docs/CONFIG-VARS.md
main.tf
modules/azure_aks/main.tf
modules/azure_aks/outputs.tf
modules/azure_aks/variables.tf
variables.tf

This PR adds support for Microsoft Entra authentication with Kubernetes RBAC. For more details on Microsoft Entra authentication with Kubernetes RBAC see Azure documentation [here](https://learn.microsoft.com/en-us/azure/aks/azure-ad-rbac).
With this new feature user will have two options to configure Authentication and Authorization in an AKS cluster:
1. Local Accounts with Kubernetes RBAC.  -- Current default
2. Microsoft Entra authentication with Kubernetes RBAC.
Verified following scenarios:
|Scenario|Task|Cadence|kubernetes_version|Notes|
|:----|:----|:----|:----|:----|
|1|create_static_kubeconfig = true, rbac_aad_enabled = true, rbac_aad_admin_group_object_ids = ["****"]|fast:2020|1.28|Authentication and Authorization is set to `Microsoft Entra authentication with Kubernetes RBAC`| …

feat: (IAC-600) Add support for Microsoft Entra authentication with Kubernetes RBAC

---

docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-postgres.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azurerm_postgresql_flex/variables.tf
modules/azurerm_vm/variables.tf
variables.tf

Updated examples, defaults, and docs to line up with sizing recommendations.
| Scenario | Provider | Example File                    | kubernetes_version | Order  | Cadence   |
|----------|----------|---------------------------------|--------------------|--------|-----------|
| 1        | Azure    | sample-input.tfvars             | v1.28.9            | * | fast:2020 |
| 2        | Azure    | sample-input-connect.tfvars     | v1.28.9            |        |           |
| 3        | Azure    | sample-input-defaults.tfvars    | v1.28.9            |        |           |
| 4        | Azure    | sample-input-minimal.tfvars     | v1.28.9            |        |           |
| 5        | Azure    | sample-input-ppg.tfvars         | v1.28.9            |        |           |
| 6        | Azure    | …

feat: (IAC-1024) Update IAC Sample Sizing

---

container-structure-test.yaml

The GitHub Workflow action for container-structure-test fails as the path for AZ has been updated.
Earlier the az cli would get installed here: `/usr/local/bin/az` whereas with the new az cli v2.64.0 that location has been updated to `/usr/bin/az`.
This change updates the container-structure-test with correct path to fix the failing GitHub action.

fix: (PSKD-886) Update AZ cli path for container-structure-test

---

linting-configs/.tflint.hcl

The TFLint config; "module" attribute was removed in v0.54.0. Updated code to use "call_module_type" instead.

fix: (PSKD-815) Update tflint module error

---

Dockerfile

"chmod" command in Dockerfile moved after the "terraform init" command to allow for overriding the default local backend.

fix: (PSKD-903) permissions set in dockerfile

---

modules/azurerm_postgresql_flex/main.tf

This PR adds public_network_access_enabled var to azurerm_postgresql_flexible_server module, derived from the existing connectivity_method var.  No new input variables.  
Testing this with `postgres_servers.default.connectivity_method: private` produced a private flexpsql server as expected.  
Testing with `postgres_servers.default.connectivity_method: public` has not been completed yet

fix: (PSKD-975) Add public_network_access_enabled to azurerm_postgresql_flexible_server resource

---

.github/workflows/linter-analysis.yaml

The required linters are not running on pull requests from forked repositories. This fix is intended to trigger the linters on any pull request going to the main or staging branch.
Targeting the main branch so the workflow changes are immediate. Otherwise we will have to wait for the next release.

ci: update linter to run on pull requests to main and staging

---

main.tf
modules/aks_node_pool/main.tf
modules/aks_node_pool/variables.tf
modules/azure_aks/main.tf
modules/azure_aks/variables.tf
variables.tf

Added option to specify the name of **node_resource_group**.
The default is set to be the the original format that starts with MC.
According https://learn.microsoft.com/en-us/azure/aks/faq#why-are-two-resource-groups-created-with-aks, the default name of node resource group is in a format of MC_myResourceGroup_myAKSCluster_eastus. 
Introduced in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster, the optional argument node_resource_group allows user to specify the name of name of **node_resource_group**.

Added option to specify the name of node_resource_group

---

.gitignore
main.tf
test/defaultplan/defaults_test.go
test/nondefaultplan/azure_policy_test.go

Adding default and non default unit test case for https://github.com/sassoftware/viya4-iac-azure/pull/389 
- test/defaultplan/defaults_test.go - check aks_azure_policy_enabled returns false
- test/nondefaultplan/azure_policy_test.go - set aks_azure_policy_enabled to true, check returns true
Additional changes:
- main.tf - logic to set aks_azure_policy_enabled to false if not explicitly defined in tfvars file
- defaults_test.go - renaming some tests that make more sense
- .gitignore - fix typo test/test_output to test/testoutput

test: (PSKD-1556) add default and non default test for aks_azure_policy_enabled

---

test/nondefaultplan/rbac_test.go

* Given the go test command run filter in our GitHub action, all unit tests funcs should start with TestPlan.
* GitHub Default Plan Unit Tests run showing execution of all 3 TestPlanRbac*  non-default tests https://github.com/sassoftware/viya4-iac-azure/actions/runs/14471757416

Default plan unit test names should start with TestPlan (PSKD-1486)

---

docs/CONFIG-VARS.md
variables.tf

Removing the `PLPGSQL` azure.extension from the default Azure Flexible Server configuration. [Azure has change the behavior](https://learn.microsoft.com/en-us/answers/questions/2259086/plpgsql-not-working-on-postgres-16-8-for-flexi-ser) of this extension so it's enabled by default. As such, it's no longer an option, which causes Terraform to fail.
|Scenario|Task|Provider|Cadence|kubernetes_version|Deploy method|Database Type|Notes|
|:----|:----|:----|:----|:----|:----|:----|:----|
|1|OOTB|Azure|stable:2025.03|1.31|docker, DO: true|External|

fix: remove PLPGSQL azure extension (PSKD-1642)

---

docs/community/community_config_vars.md
main.tf
modules/azurerm_netapp/main.tf
modules/azurerm_netapp/variables.tf
variables.tf

Added the option `contrib_netapp_volume_size` a number optional field that will specify an alternative size of the netapp volume created when HA with Netapp Volumes are specified. This is to address #482.
The default value for the field is 0 which when this is specified the volume size will match the pool size which is the current implementation.

feat: Adding community option for Azure NetappFiles Volume size control.

---

.github/dependabot.yml
.github/workflows/conventional-commits.yml
.github/workflows/linter-analysis.yml

Update workflows that were targeting staging. They will now target the main branch.

chore: update workflows to point to main

---

modules/aks_node_pool/main.tf
modules/azurerm_vm/main.tf

- Only create a `linux_os_config` block for a node pool if a value has been explicitly set for `vm_max_map_count` for that node pool.
- Add `temporary_name_for_rotation` argument to handle changes to the `linux_os_config` value when applied to the same cluster.
- This azure_rm issue https://github.com/hashicorp/terraform-provider-azurerm/issues/29276 requires adding a lifecycle clause to ignore azurerm_vm identity changes until the provider publishes a fix for the issue. This issue is independent of #499 but exposed another problem that we need to account for when running apply against an existing cluster.
| Scenario | Method          | Apply Sequence | Provider | K8s Version | vm_max_map_count                     | Notes …

fix: IaC Azure requires 'temporary_name_for_rotation' during update

---

docs/CONFIG-VARS.md
modules/azurerm_vm/main.tf

fixes #506 
Update the FIPS image to the proper "pro-fips-22_04" rather than the invalid "pro-fips-22_04-gen2"
I was able to create a FIPS-enabled cluster and deploy Viya into it.

fix: update FIPS vm image

---

README.md

This PR fixes a broken link in the viya4-iac-azure project that pointed to the "Getting Started with SAS Viya and Azure Kubernetes Service" section in the SAS Viya Platform Operations documentation. The outdated URL has been replaced with the correct, working link.

fix: getting started with SAS viya and K8s service link (PSCLOUD-132)
