main.tf

Added coalesce to subnet_names removing warning.

---

main.tf

Removed logic check for 'terraform' that was causing the error.

---

docs/CONFIG-VARS.md
examples/sample-input-ha.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
main.tf
modules/aks_node_pool/main.tf
modules/aks_node_pool/variables.tf
modules/azure_aks/main.tf
modules/azure_aks/variables.tf
monitor.tf
variables.tf

aks advanced network and nodepools config options

---

docs/CONFIG-VARS.md

Add RAID5 help text

---

README.md
docs/CONFIG-VARS.md
docs/user/AzureHelpTopics.md
docs/user/DockerUsage.md
docs/user/TerraformAzureAuthentication.md
docs/user/TerraformUsage.md

- Add IaC description in README.md
- close #71 
- Update Docker usage docs, simplify TerraformAzureAuthentication

Doc updates

---

docs/CONFIG-VARS.md
examples/sample-input-ha.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
modules/azure_aks/main.tf
variables.tf

Also added in required system nodepool default label: `"kubernetes.azure.com/mode" = "system"`

Removed workload.sas.com/node from code/doc.

---

README.md
cloud-init/jump/cloud-config
cloud-init/nfs/cloud-config
docs/CONFIG-VARS.md
examples/sample-input-ha.tfvars
files/iac_git_info.sh
files/iac_tooling_version.sh
main.tf
modules/azurerm_vm/main.tf
modules/azurerm_vm/variables.tf
outputs.tf
variables.tf

Changed vm os from centos -> ubuntu
Updated cloud-inits for jump/nfs vms
Updated configMap removing git requirement

Updated vm os, git check, and cloud-init

---

README.md
docs/CONFIG-VARS.md
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
main.tf
modules/azurerm_vm/main.tf
modules/azurerm_vm/variables.tf
variables.tf

closes #81 and #84
- surface variables to configure VM types for Jump & NFS
- changed defaults SKUs
- adjust other values for networking/cahching when using Ultra disk

Vm disk config

---

docs/CONFIG-VARS.md
examples/sample-input.tfvars
variables.tf

**NOTE** - VM for NFS server was reverted back to its correct value in the docs.

Fixes: #116 - nfs vm machine type has been corrected.

---

.dockerignore
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
main.tf
modules/azurerm_netapp/main.tf
modules/azurerm_netapp/outputs.tf
modules/azurerm_netapp/variables.tf
modules/azurerm_network_security_group/main.tf
modules/azurerm_network_security_group/outputs.tf
modules/azurerm_network_security_group/variables.tf
modules/azurerm_resource_group/main.tf
modules/azurerm_resource_group/outputs.tf
modules/azurerm_resource_group/variables.tf
modules/azurerm_vnet/main.tf
modules/azurerm_vnet/outputs.tf
modules/azurerm_vnet/variables.tf
monitor.tf
outputs.tf
variables.tf
versions.tf

Add support for providing pre-existing rg, vnet and subnets
closes #127 #114

Support bring your own

---

main.tf

improve ordering

---

docs/user/TerraformUsage.md

Fix path to the helper script ... add `/tools/` to path

Fix path to the helper script

---

.hadolint.yaml
.shellcheckrc
.tflint.hcl
Dockerfile
docker-entrypoint.sh
files/tools/iac_tooling_version.sh
files/tools/terraform_env_variable_helper.sh

This PR includes fixes for linting errors found during development of IaC CI/CD pipeline commit checks

Linter fixes to enable linter commit checks

---

files/tools/terraform_env_variable_helper.sh

Allow helper script to be sourced

Allow helper script to be sourced

---

docs/CONFIG-VARS.md

Fixes #160 - Addressing mismatched items.

Fixed issues identified in #160

---

outputs.tf

Fix sensitive tf outputs

---

main.tf

Fix security group condition for #156

---

.github/ISSUE_TEMPLATE/issue--bug-report.md

Adding in a new issue template for reporting bugs.

Update issue templates

---

modules/azurerm_vm/main.tf

Closes: #140 - Added dependency to fix nic issue.

Fixing nic error.

---

files/tools/terraform_env_variable_helper.sh

AZ CLI has a breaking change ... the updates to the script worked as expected for myself and Tom S

resolve AZ CLI Change

---

files/cloud-init/nfs/cloud-config
main.tf

use subnet cidrs for nfs exports instead of first vnet cidr

---

docs/user/BYOnetwork.md

(IAC-374) Update BYO Subnet Documentation #227

Monthly Release - 4.5.0

---

Dockerfile

Fixes this issue : https://github.blog/2022-04-12-git-security-vulnerability-announced/

(IAC-530) added git share directive for viya4-iac-azure

---

docs/sas-updates.md

New Readme document has been added for the remove connect class reference.

(IAC-533) New Readme for remove connect class

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
variables.tf

(IAC-543) Azure - support for k8s 1.23 and dropping 1.20 in June cadence [#237](https://github.com/sassoftware/viya4-iac-azure/pull/237)

5.1.0 - June 17, 2022

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
modules/kubeconfig/main.tf
variables.tf
versions.tf

5.3.0 - September 01, 2022

---

README.md
docs/CONFIG-VARS.md
examples/sample-input-singlestore.tfvars
main.tf
modules/aks_node_pool/main.tf
modules/aks_node_pool/variables.tf
modules/azure_aks/main.tf
modules/azurerm_vm/main.tf
modules/azurerm_vm/variables.tf
modules/azurerm_vnet/main.tf
modules/azurerm_vnet/variables.tf
outputs.tf
variables.tf
versions.tf
vms.tf

Upgrade `azurerm` provider version from 2.62.0 to 3.21.1. Followed the upgrade document [3.0-upgrade-guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide)
Following Scenarios were verified. Cluster creation was successful for all the scenarios. See internal ticket for details.
1. All defaults
2. Azure monitor enabled: create_aks_azure_monitor = true
3. create_container_registry = true, container_registry_sku = "Premium" and container_registry_geo_replica_locs = ["eastus", "southcentralus"]
4. create_container_registry = true, container_registry_sku = "Premium", container_registry_geo_replica_locs = null
5. default_nodepool_availability_zones = ["1","2"]

feat: (IAC-403): Update AzureRM Terraform provider version

---

README.md

docs: (IAC-487) Update README.md

---

README.md
docs/CONFIG-VARS.md
main.tf
modules/azure_aks/main.tf
modules/azure_aks/variables.tf
variables.tf

6.1.0 - December 19, 2022 

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
files/cloud-init/nfs/cloud-config
main.tf
modules/azure_aks/variables.tf
monitor.tf
variables.tf

- #276
- #278 
- #280
- #281
- #282

6.2.0 - February 17, 2023

---

Dockerfile
README.md
docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azure_aks/variables.tf
variables.tf

6.3.0 - March 16, 2023

---

docs/user/AzureHelpTopics.md

Some of the commands in the `AzureHelpTopics.md` document were outdated. Updated the commands related to Service Principal creation.

docs: (IAC-372) Updated the commands related to Service Principal creation

---

docs/CONFIG-VARS.md
variables.tf

This PR documents FIPS support which was enabled as experimental feature through #288.
Cluster creation with FIPS enabled was successful. SAS Viya Platform deployment completed successfully however, few services are still in progress to consume the FIPS changes.

docs: (IAC-1064) Document FIPS support

---

docs/CONFIG-VARS.md
variables.tf

7.1.0 - June 15, 2023

---

Dockerfile

To remediate the high security vulnerabilities updated the Dockerfile to add `apk upgrade` which upgrades the installed packages to the latest version available from configured package repositories.
Verified following scenario, see details in internal ticket:
| Scenario | Provider | Kubernetes Version  | Deployment Method | Notes |
|:----|:----|:----|:----|:----|
| 1        | Azure      | 1.26 | Docker | Cluster created successfully|

feat: (IAC-1035) Remediate high security vulnerabilities

---

docs/CONFIG-VARS.md
docs/Troubleshooting.md
files/cloud-init/jump/cloud-config
files/cloud-init/nfs/cloud-config
main.tf
modules/azurerm_message_broker/main.tf
modules/azurerm_message_broker/outputs.tf
modules/azurerm_message_broker/variables.tf
modules/azurerm_netapp/variables.tf
outputs.tf
variables.tf
versions.tf
vms.tf

- #320 
- #325 
- #327 
- #329

8.0.0 - July 20, 2023

---

docs/Troubleshooting.md

Updated importing azure resource example in Troubleshooting.md based on User's request in PR #253.

docs: (IAC-1112) Updated importing azure resource example in Troubleshooting.md

---

docs/CONFIG-VARS.md
examples/sample-input-byo.tfvars
examples/sample-input-connect.tfvars
examples/sample-input-ha.tfvars
examples/sample-input-minimal.tfvars
examples/sample-input-postgres.tfvars
examples/sample-input-ppg.tfvars
examples/sample-input-singlestore.tfvars
examples/sample-input.tfvars
modules/azurerm_postgresql_flex/variables.tf
modules/azurerm_vm/variables.tf
variables.tf

9.4.0 - June 28, 2024

---

CONTRIBUTING.md
docs/CONFIG-VARS.md
test/nondefaultplan/rbac_test.go
variables.tf

10.3.1 - April 23, 2025

---

docs/CONFIG-VARS.md
modules/azurerm_vm/main.tf
modules/azurerm_vm/variables.tf

This change updates the ubuntu image version to 22.04. I chose 22.04 over 24.04 because I'm finding 22.04 and not 24.04 in the azure marketplace:
- https://azuremarketplace.microsoft.com/en-us/marketplace/apps/canonical.0001-com-ubuntu-pro-jammy?tab=Overview
Part of the review of this change should be verifying that I have chosen the correct version.

chore(deps): update vm image to ubuntu 22.04 (PSKD-1572)

---

CONTRIBUTING.md

Adding documentation steps to the CONTRIBUTING.md on how to open a PR via forking a repository

docs: steps to open a PR (PSKD-1751)

---

docs/community/community_config_vars.md
main.tf
modules/azurerm_netapp/main.tf
modules/azurerm_netapp/outputs.tf
modules/azurerm_netapp/variables.tf
test/nondefaultplan/netapp_test.go
variables.tf

Reverts sassoftware/viya4-iac-azure#527

feat: Revert Netapp BYO Components #500
